### ISSUE TITLE
Do not use toggle for likes

### ISSUE THREAD

**Issue by clubifaximatic** [drierat/kPAX2_server#10]
In my opinion is easier to understand how the API works if we have two different endopints (one endpoint for likes and another for dislike) rather than one 'like' endpoint that change the status based on previous status. This will avoid confusion and prevent unwanted behaviour.

call to like: if like already exists, do nothing

call to dislike: if like do not exists, do nothing

**Comment by mmuntanerm** [comment]
Ok 
This suggestions have been added to the last version of the server. The issues are fixed by the moment.
